prompts = [
    'add a subtle background',
    'add a subtle edges',
    'add a subtle center',
    'add a subtle subject',
    'add a subtle foreground',
    'add a subtle entire image',
    'add a subtle corners',
    'add a subtle highlights',
    'add a subtle shadows',
    'add a subtle midtones',
    'add a subtle outline',
    'add a subtle silhouette',
    'add a subtle reflection',
    'add a subtle texture',
    'add a subtle color palette',
    'add a subtle contrast',
    'add a subtle brightness',
    'add a subtle saturation',
    'add a subtle temperature',
    'add a subtle tone curve',
    'add a subtle hue',
    'add a subtle vibrance',
    'add a subtle clarity',
    'add a subtle structure',
    'add a subtle detail',
    'add a subtle sharpness',
    'add a subtle focus',
    'add a subtle depth of field',
    'add a subtle bokeh',
    'add a subtle motion blur',
    'add a subtle lens flare',
    'add a subtle film grain',
    'add a subtle ripple',
    'add a subtle smoke',
    'add a subtle mist',
    'add a subtle fog',
    'add a subtle bubble',
    'add a subtle particle',
    'add a subtle sparkle',
    'add a subtle confetti',
    'add a subtle raindrop',
    'add a subtle snow overlay',
    'add a subtle light leak',
    'add a subtle sun flare',
    'add a subtle neon glow',
    'add a subtle cartoon outline',
    'add a subtle pencil sketch',
    'add a subtle charcoal sketch',
    'add a subtle pastel effect',
    'add a subtle chalk scribble',
    'add a subtle blueprint grid',
    'add a subtle circuit pattern',
    'add a subtle torn paper',
    'add a subtle crumpled paper',
    'add a subtle old photo border',
    'add a subtle Polaroid frame',
    'add a subtle vintage frame',
    'add a subtle matte painting',
    'add a subtle watercolor splash',
    'add a subtle ink blot',
    'add a subtle stain',
    'add a subtle streak',
    'add a subtle drop shadow',
    'add a subtle mirror reflection',
    'add a subtle thermal map',
    'add a subtle infrared map',
    'add a subtle X-ray effect',
    'add a subtle UV effect',
    'add a subtle comic bubble',
    'add a subtle speech bubble',
    'add a subtle barcode',
    'add a subtle QR code',
    'add a subtle wireframe overlay',
    'add a subtle 3D cube',
    'add a subtle 3D sphere',
    'add a subtle 3D cylinder',
    'add a subtle 3D pyramid',
    'add a subtle 3D cone',
    'add a subtle 3D torus',
    'add a soft background',
    'add a soft edges',
    'add a soft center',
    'add a soft subject',
    'add a soft foreground',
    'add a soft entire image',
    'add a soft corners',
    'add a soft highlights',
    'add a soft shadows',
    'add a soft midtones',
    'add a soft outline',
    'add a soft silhouette',
    'add a soft reflection',
    'add a soft texture',
    'add a soft color palette',
    'add a soft contrast',
    'add a soft brightness',
    'add a soft saturation',
    'add a soft temperature',
    'add a soft tone curve',
    'add a soft hue',
    'add a soft vibrance',
    'add a soft clarity',
    'add a soft structure',
    'add a soft detail',
    'add a soft sharpness',
    'add a soft focus',
    'add a soft depth of field',
    'add a soft bokeh',
    'add a soft motion blur',
    'add a soft lens flare',
    'add a soft film grain',
    'add a soft ripple',
    'add a soft smoke',
    'add a soft mist',
    'add a soft fog',
    'add a soft bubble',
    'add a soft particle',
    'add a soft sparkle',
    'add a soft confetti',
    'add a soft raindrop',
    'add a soft snow overlay',
    'add a soft light leak',
    'add a soft sun flare',
    'add a soft neon glow',
    'add a soft cartoon outline',
    'add a soft pencil sketch',
    'add a soft charcoal sketch',
    'add a soft pastel effect',
    'add a soft chalk scribble',
    'add a soft blueprint grid',
    'add a soft circuit pattern',
    'add a soft torn paper',
    'add a soft crumpled paper',
    'add a soft old photo border',
    'add a soft Polaroid frame',
    'add a soft vintage frame',
    'add a soft matte painting',
    'add a soft watercolor splash',
    'add a soft ink blot',
    'add a soft stain',
    'add a soft streak',
    'add a soft drop shadow',
    'add a soft mirror reflection',
    'add a soft thermal map',
    'add a soft infrared map',
    'add a soft X-ray effect',
    'add a soft UV effect',
    'add a soft comic bubble',
    'add a soft speech bubble',
    'add a soft barcode',
    'add a soft QR code',
    'add a soft wireframe overlay',
    'add a soft 3D cube',
    'add a soft 3D sphere',
    'add a soft 3D cylinder',
    'add a soft 3D pyramid',
    'add a soft 3D cone',
    'add a soft 3D torus',
    'add a strong background',
    'add a strong edges',
    'add a strong center',
    'add a strong subject',
    'add a strong foreground',
    'add a strong entire image',
    'add a strong corners',
    'add a strong highlights',
    'add a strong shadows',
    'add a strong midtones',
    'add a strong outline',
    'add a strong silhouette',
    'add a strong reflection',
    'add a strong texture',
    'add a strong color palette',
    'add a strong contrast',
    'add a strong brightness',
    'add a strong saturation',
    'add a strong temperature',
    'add a strong tone curve',
    'add a strong hue',
    'add a strong vibrance',
    'add a strong clarity',
    'add a strong structure',
    'add a strong detail',
    'add a strong sharpness',
    'add a strong focus',
    'add a strong depth of field',
    'add a strong bokeh',
    'add a strong motion blur',
    'add a strong lens flare',
    'add a strong film grain',
    'add a strong ripple',
    'add a strong smoke',
    'add a strong mist',
    'add a strong fog',
    'add a strong bubble',
    'add a strong particle',
    'add a strong sparkle',
    'add a strong confetti',
    'add a strong raindrop',
    'add a strong snow overlay',
    'add a strong light leak',
    'add a strong sun flare',
    'add a strong neon glow',
    'add a strong cartoon outline',
    'add a strong pencil sketch',
    'add a strong charcoal sketch',
    'add a strong pastel effect',
    'add a strong chalk scribble',
    'add a strong blueprint grid',
    'add a strong circuit pattern',
    'add a strong torn paper',
    'add a strong crumpled paper',
    'add a strong old photo border',
    'add a strong Polaroid frame',
    'add a strong vintage frame',
    'add a strong matte painting',
    'add a strong watercolor splash',
    'add a strong ink blot',
    'add a strong stain',
    'add a strong streak',
    'add a strong drop shadow',
    'add a strong mirror reflection',
    'add a strong thermal map',
    'add a strong infrared map',
    'add a strong X-ray effect',
    'add a strong UV effect',
    'add a strong comic bubble',
    'add a strong speech bubble',
    'add a strong barcode',
    'add a strong QR code',
    'add a strong wireframe overlay',
    'add a strong 3D cube',
    'add a strong 3D sphere',
    'add a strong 3D cylinder',
    'add a strong 3D pyramid',
    'add a strong 3D cone',
    'add a strong 3D torus',
    'add a dramatic background',
    'add a dramatic edges',
    'add a dramatic center',
    'add a dramatic subject',
    'add a dramatic foreground',
    'add a dramatic entire image',
    'add a dramatic corners',
    'add a dramatic highlights',
    'add a dramatic shadows',
    'add a dramatic midtones',
    'add a dramatic outline',
    'add a dramatic silhouette',
    'add a dramatic reflection',
    'add a dramatic texture',
    'add a dramatic color palette',
    'add a dramatic contrast',
    'add a dramatic brightness',
    'add a dramatic saturation',
    'add a dramatic temperature',
    'add a dramatic tone curve',
    'add a dramatic hue',
    'add a dramatic vibrance',
    'add a dramatic clarity',
    'add a dramatic structure',
    'add a dramatic detail',
    'add a dramatic sharpness',
    'add a dramatic focus',
    'add a dramatic depth of field',
    'add a dramatic bokeh',
    'add a dramatic motion blur',
    'add a dramatic lens flare',
    'add a dramatic film grain',
    'add a dramatic ripple',
    'add a dramatic smoke',
    'add a dramatic mist',
    'add a dramatic fog',
    'add a dramatic bubble',
    'add a dramatic particle',
    'add a dramatic sparkle',
    'add a dramatic confetti',
    'add a dramatic raindrop',
    'add a dramatic snow overlay',
    'add a dramatic light leak',
    'add a dramatic sun flare',
    'add a dramatic neon glow',
    'add a dramatic cartoon outline',
    'add a dramatic pencil sketch',
    'add a dramatic charcoal sketch',
    'add a dramatic pastel effect',
    'add a dramatic chalk scribble',
    'add a dramatic blueprint grid',
    'add a dramatic circuit pattern',
    'add a dramatic torn paper',
    'add a dramatic crumpled paper',
    'add a dramatic old photo border',
    'add a dramatic Polaroid frame',
    'add a dramatic vintage frame',
    'add a dramatic matte painting',
    'add a dramatic watercolor splash',
    'add a dramatic ink blot',
    'add a dramatic stain',
    'add a dramatic streak',
    'add a dramatic drop shadow',
    'add a dramatic mirror reflection',
    'add a dramatic thermal map',
    'add a dramatic infrared map',
    'add a dramatic X-ray effect',
    'add a dramatic UV effect',
    'add a dramatic comic bubble',
    'add a dramatic speech bubble',
    'add a dramatic barcode',
    'add a dramatic QR code',
    'add a dramatic wireframe overlay',
    'add a dramatic 3D cube',
    'add a dramatic 3D sphere',
    'add a dramatic 3D cylinder',
    'add a dramatic 3D pyramid',
    'add a dramatic 3D cone',
    'add a dramatic 3D torus',
    'add a faint background',
    'add a faint edges',
    'add a faint center',
    'add a faint subject',
    'add a faint foreground',
    'add a faint entire image',
    'add a faint corners',
    'add a faint highlights',
    'add a faint shadows',
    'add a faint midtones',
    'add a faint outline',
    'add a faint silhouette',
    'add a faint reflection',
    'add a faint texture',
    'add a faint color palette',
    'add a faint contrast',
    'add a faint brightness',
    'add a faint saturation',
    'add a faint temperature',
    'add a faint tone curve',
    'add a faint hue',
    'add a faint vibrance',
    'add a faint clarity',
    'add a faint structure',
    'add a faint detail',
    'add a faint sharpness',
    'add a faint focus',
    'add a faint depth of field',
    'add a faint bokeh',
    'add a faint motion blur',
    'add a faint lens flare',
    'add a faint film grain',
    'add a faint ripple',
    'add a faint smoke',
    'add a faint mist',
    'add a faint fog',
    'add a faint bubble',
    'add a faint particle',
    'add a faint sparkle',
    'add a faint confetti',
    'add a faint raindrop',
    'add a faint snow overlay',
    'add a faint light leak',
    'add a faint sun flare',
    'add a faint neon glow',
    'add a faint cartoon outline',
    'add a faint pencil sketch',
    'add a faint charcoal sketch',
    'add a faint pastel effect',
    'add a faint chalk scribble',
    'add a faint blueprint grid',
    'add a faint circuit pattern',
    'add a faint torn paper',
    'add a faint crumpled paper',
    'add a faint old photo border',
    'add a faint Polaroid frame',
    'add a faint vintage frame',
    'add a faint matte painting',
    'add a faint watercolor splash',
    'add a faint ink blot',
    'add a faint stain',
    'add a faint streak',
    'add a faint drop shadow',
    'add a faint mirror reflection',
    'add a faint thermal map',
    'add a faint infrared map',
    'add a faint X-ray effect',
    'add a faint UV effect',
    'add a faint comic bubble',
    'add a faint speech bubble',
    'add a faint barcode',
    'add a faint QR code',
    'add a faint wireframe overlay',
    'add a faint 3D cube',
    'add a faint 3D sphere',
    'add a faint 3D cylinder',
    'add a faint 3D pyramid',
    'add a faint 3D cone',
    'add a faint 3D torus',
    'add a intense background',
    'add a intense edges',
    'add a intense center',
    'add a intense subject',
    'add a intense foreground',
    'add a intense entire image',
    'add a intense corners',
    'add a intense highlights',
    'add a intense shadows',
    'add a intense midtones',
    'add a intense outline',
    'add a intense silhouette',
    'add a intense reflection',
    'add a intense texture',
    'add a intense color palette',
    'add a intense contrast',
    'add a intense brightness',
    'add a intense saturation',
    'add a intense temperature',
    'add a intense tone curve',
    'add a intense hue',
    'add a intense vibrance',
    'add a intense clarity',
    'add a intense structure',
    'add a intense detail',
    'add a intense sharpness',
    'add a intense focus',
    'add a intense depth of field',
    'add a intense bokeh',
    'add a intense motion blur',
    'add a intense lens flare',
    'add a intense film grain',
    'add a intense ripple',
    'add a intense smoke',
    'add a intense mist',
    'add a intense fog',
    'add a intense bubble',
    'add a intense particle',
    'add a intense sparkle',
    'add a intense confetti',
    'add a intense raindrop',
    'add a intense snow overlay',
    'add a intense light leak',
    'add a intense sun flare',
    'add a intense neon glow',
    'add a intense cartoon outline',
    'add a intense pencil sketch',
    'add a intense charcoal sketch',
    'add a intense pastel effect',
    'add a intense chalk scribble',
    'add a intense blueprint grid',
    'add a intense circuit pattern',
    'add a intense torn paper',
    'add a intense crumpled paper',
    'add a intense old photo border',
    'add a intense Polaroid frame',
    'add a intense vintage frame',
    'add a intense matte painting',
    'add a intense watercolor splash',
    'add a intense ink blot',
    'add a intense stain',
    'add a intense streak',
    'add a intense drop shadow',
    'add a intense mirror reflection',
    'add a intense thermal map',
    'add a intense infrared map',
    'add a intense X-ray effect',
    'add a intense UV effect',
    'add a intense comic bubble',
    'add a intense speech bubble',
    'add a intense barcode',
    'add a intense QR code',
    'add a intense wireframe overlay',
    'add a intense 3D cube',
    'add a intense 3D sphere',
    'add a intense 3D cylinder',
    'add a intense 3D pyramid',
    'add a intense 3D cone',
    'add a intense 3D torus',
    'add a vivid background',
    'add a vivid edges',
    'add a vivid center',
    'add a vivid subject',
    'add a vivid foreground',
    'add a vivid entire image',
    'add a vivid corners',
    'add a vivid highlights',
    'add a vivid shadows',
    'add a vivid midtones',
    'add a vivid outline',
    'add a vivid silhouette',
    'add a vivid reflection',
    'add a vivid texture',
    'add a vivid color palette',
    'add a vivid contrast',
    'add a vivid brightness',
    'add a vivid saturation',
    'add a vivid temperature',
    'add a vivid tone curve',
    'add a vivid hue',
    'add a vivid vibrance',
    'add a vivid clarity',
    'add a vivid structure',
    'add a vivid detail',
    'add a vivid sharpness',
    'add a vivid focus',
    'add a vivid depth of field',
    'add a vivid bokeh',
    'add a vivid motion blur',
    'add a vivid lens flare',
    'add a vivid film grain',
    'add a vivid ripple',
    'add a vivid smoke',
    'add a vivid mist',
    'add a vivid fog',
    'add a vivid bubble',
    'add a vivid particle',
    'add a vivid sparkle',
    'add a vivid confetti',
    'add a vivid raindrop',
    'add a vivid snow overlay',
    'add a vivid light leak',
    'add a vivid sun flare',
    'add a vivid neon glow',
    'add a vivid cartoon outline',
    'add a vivid pencil sketch',
    'add a vivid charcoal sketch',
    'add a vivid pastel effect',
    'add a vivid chalk scribble',
    'add a vivid blueprint grid',
    'add a vivid circuit pattern',
    'add a vivid torn paper',
    'add a vivid crumpled paper',
    'add a vivid old photo border',
    'add a vivid Polaroid frame',
    'add a vivid vintage frame',
    'add a vivid matte painting',
    'add a vivid watercolor splash',
    'add a vivid ink blot',
    'add a vivid stain',
    'add a vivid streak',
    'add a vivid drop shadow',
    'add a vivid mirror reflection',
    'add a vivid thermal map',
    'add a vivid infrared map',
    'add a vivid X-ray effect',
    'add a vivid UV effect',
    'add a vivid comic bubble',
    'add a vivid speech bubble',
    'add a vivid barcode',
    'add a vivid QR code',
    'add a vivid wireframe overlay',
    'add a vivid 3D cube',
    'add a vivid 3D sphere',
    'add a vivid 3D cylinder',
    'add a vivid 3D pyramid',
    'add a vivid 3D cone',
    'add a vivid 3D torus',
    'add a muted background',
    'add a muted edges',
    'add a muted center',
    'add a muted subject',
    'add a muted foreground',
    'add a muted entire image',
    'add a muted corners',
    'add a muted highlights',
    'add a muted shadows',
    'add a muted midtones',
    'add a muted outline',
    'add a muted silhouette',
    'add a muted reflection',
    'add a muted texture',
    'add a muted color palette',
    'add a muted contrast',
    'add a muted brightness',
    'add a muted saturation',
    'add a muted temperature',
    'add a muted tone curve',
    'add a muted hue',
    'add a muted vibrance',
    'add a muted clarity',
    'add a muted structure',
    'add a muted detail',
    'add a muted sharpness',
    'add a muted focus',
    'add a muted depth of field',
    'add a muted bokeh',
    'add a muted motion blur',
    'add a muted lens flare',
    'add a muted film grain',
    'add a muted ripple',
    'add a muted smoke',
    'add a muted mist',
    'add a muted fog',
    'add a muted bubble',
    'add a muted particle',
    'add a muted sparkle',
    'add a muted confetti',
    'add a muted raindrop',
    'add a muted snow overlay',
    'add a muted light leak',
    'add a muted sun flare',
    'add a muted neon glow',
    'add a muted cartoon outline',
    'add a muted pencil sketch',
    'add a muted charcoal sketch',
    'add a muted pastel effect',
    'add a muted chalk scribble',
    'add a muted blueprint grid',
    'add a muted circuit pattern',
    'add a muted torn paper',
    'add a muted crumpled paper',
    'add a muted old photo border',
    'add a muted Polaroid frame',
    'add a muted vintage frame',
    'add a muted matte painting',
    'add a muted watercolor splash',
    'add a muted ink blot',
    'add a muted stain',
    'add a muted streak',
    'add a muted drop shadow',
    'add a muted mirror reflection',
    'add a muted thermal map',
    'add a muted infrared map',
    'add a muted X-ray effect',
    'add a muted UV effect',
    'add a muted comic bubble',
    'add a muted speech bubble',
    'add a muted barcode',
    'add a muted QR code',
    'add a muted wireframe overlay',
    'add a muted 3D cube',
    'add a muted 3D sphere',
    'add a muted 3D cylinder',
    'add a muted 3D pyramid',
    'add a muted 3D cone',
    'add a muted 3D torus',
    'add a dark background',
    'add a dark edges',
    'add a dark center',
    'add a dark subject',
    'add a dark foreground',
    'add a dark entire image',
    'add a dark corners',
    'add a dark highlights',
    'add a dark shadows',
    'add a dark midtones',
    'add a dark outline',
    'add a dark silhouette',
    'add a dark reflection',
    'add a dark texture',
    'add a dark color palette',
    'add a dark contrast',
    'add a dark brightness',
    'add a dark saturation',
    'add a dark temperature',
    'add a dark tone curve',
    'add a dark hue',
    'add a dark vibrance',
    'add a dark clarity',
    'add a dark structure',
    'add a dark detail',
    'add a dark sharpness',
    'add a dark focus',
    'add a dark depth of field',
    'add a dark bokeh',
    'add a dark motion blur',
    'add a dark lens flare',
    'add a dark film grain',
    'add a dark ripple',
    'add a dark smoke',
    'add a dark mist',
    'add a dark fog',
    'add a dark bubble',
    'add a dark particle',
    'add a dark sparkle',
    'add a dark confetti',
    'add a dark raindrop',
    'add a dark snow overlay',
    'add a dark light leak',
    'add a dark sun flare',
    'add a dark neon glow',
    'add a dark cartoon outline',
    'add a dark pencil sketch',
    'add a dark charcoal sketch',
    'add a dark pastel effect',
    'add a dark chalk scribble',
    'add a dark blueprint grid',
    'add a dark circuit pattern',
    'add a dark torn paper',
    'add a dark crumpled paper',
    'add a dark old photo border',
    'add a dark Polaroid frame',
    'add a dark vintage frame',
    'add a dark matte painting',
    'add a dark watercolor splash',
    'add a dark ink blot',
    'add a dark stain',
    'add a dark streak',
    'add a dark drop shadow',
    'add a dark mirror reflection',
    'add a dark thermal map',
    'add a dark infrared map',
    'add a dark X-ray effect',
    'add a dark UV effect',
    'add a dark comic bubble',
    'add a dark speech bubble',
    'add a dark barcode',
    'add a dark QR code',
    'add a dark wireframe overlay',
    'add a dark 3D cube',
    'add a dark 3D sphere',
    'add a dark 3D cylinder',
    'add a dark 3D pyramid',
    'add a dark 3D cone',
    'add a dark 3D torus',
    'add a bright background',
    'add a bright edges',
    'add a bright center',
    'add a bright subject',
    'add a bright foreground',
    'add a bright entire image',
    'add a bright corners',
    'add a bright highlights',
    'add a bright shadows',
    'add a bright midtones',
    'add a bright outline',
    'add a bright silhouette',
    'add a bright reflection',
    'add a bright texture',
    'add a bright color palette',
    'add a bright contrast',
    'add a bright brightness',
    'add a bright saturation',
    'add a bright temperature',
    'add a bright tone curve',
    'add a bright hue',
    'add a bright vibrance',
    'add a bright clarity',
    'add a bright structure',
    'add a bright detail',
    'add a bright sharpness',
    'add a bright focus',
    'add a bright depth of field',
    'add a bright bokeh',
    'add a bright motion blur',
    'add a bright lens flare',
    'add a bright film grain',
    'add a bright ripple',
    'add a bright smoke',
    'add a bright mist',
    'add a bright fog',
    'add a bright bubble',
    'add a bright particle',
    'add a bright sparkle',
    'add a bright confetti',
    'add a bright raindrop',
    'add a bright snow overlay',
    'add a bright light leak',
    'add a bright sun flare',
    'add a bright neon glow',
    'add a bright cartoon outline',
    'add a bright pencil sketch',
    'add a bright charcoal sketch',
    'add a bright pastel effect',
    'add a bright chalk scribble',
    'add a bright blueprint grid',
    'add a bright circuit pattern',
    'add a bright torn paper',
    'add a bright crumpled paper',
    'add a bright old photo border',
    'add a bright Polaroid frame',
    'add a bright vintage frame',
    'add a bright matte painting',
    'add a bright watercolor splash',
    'add a bright ink blot',
    'add a bright stain',
    'add a bright streak',
    'add a bright drop shadow',
    'add a bright mirror reflection',
    'add a bright thermal map',
    'add a bright infrared map',
    'add a bright X-ray effect',
    'add a bright UV effect',
    'add a bright comic bubble',
    'add a bright speech bubble',
    'add a bright barcode',
    'add a bright QR code',
    'add a bright wireframe overlay',
    'add a bright 3D cube',
    'add a bright 3D sphere',
    'add a bright 3D cylinder',
    'add a bright 3D pyramid',
    'add a bright 3D cone',
    'add a bright 3D torus',
    'add a pastel background',
    'add a pastel edges',
    'add a pastel center',
    'add a pastel subject',
    'add a pastel foreground',
    'add a pastel entire image',
    'add a pastel corners',
    'add a pastel highlights',
    'add a pastel shadows',
    'add a pastel midtones',
    'add a pastel outline',
    'add a pastel silhouette',
    'add a pastel reflection',
    'add a pastel texture',
    'add a pastel color palette',
    'add a pastel contrast',
    'add a pastel brightness',
    'add a pastel saturation',
    'add a pastel temperature',
    'add a pastel tone curve',
    'add a pastel hue',
    'add a pastel vibrance',
    'add a pastel clarity',
    'add a pastel structure',
    'add a pastel detail',
    'add a pastel sharpness',
    'add a pastel focus',
    'add a pastel depth of field',
    'add a pastel bokeh',
    'add a pastel motion blur',
    'add a pastel lens flare',
    'add a pastel film grain',
    'add a pastel ripple',
    'add a pastel smoke',
    'add a pastel mist',
    'add a pastel fog',
    'add a pastel bubble',
    'add a pastel particle',
    'add a pastel sparkle',
    'add a pastel confetti',
    'add a pastel raindrop',
    'add a pastel snow overlay',
    'add a pastel light leak',
    'add a pastel sun flare',
    'add a pastel neon glow',
    'add a pastel cartoon outline',
    'add a pastel pencil sketch',
    'add a pastel charcoal sketch',
    'add a pastel pastel effect',
    'add a pastel chalk scribble',
    'add a pastel blueprint grid',
    'add a pastel circuit pattern',
    'add a pastel torn paper',
    'add a pastel crumpled paper',
    'add a pastel old photo border',
    'add a pastel Polaroid frame',
    'add a pastel vintage frame',
    'add a pastel matte painting',
    'add a pastel watercolor splash',
    'add a pastel ink blot',
    'add a pastel stain',
    'add a pastel streak',
    'add a pastel drop shadow',
    'add a pastel mirror reflection',
    'add a pastel thermal map',
    'add a pastel infrared map',
    'add a pastel X-ray effect',
    'add a pastel UV effect',
    'add a pastel comic bubble',
    'add a pastel speech bubble',
    'add a pastel barcode',
    'add a pastel QR code',
    'add a pastel wireframe overlay',
    'add a pastel 3D cube',
    'add a pastel 3D sphere',
    'add a pastel 3D cylinder',
    'add a pastel 3D pyramid',
    'add a pastel 3D cone',
    'add a pastel 3D torus',
    'add a neon background',
    'add a neon edges',
    'add a neon center',
    'add a neon subject',
    'add a neon foreground',
    'add a neon entire image',
    'add a neon corners',
    'add a neon highlights',
    'add a neon shadows',
    'add a neon midtones',
    'add a neon outline',
    'add a neon silhouette',
    'add a neon reflection',
    'add a neon texture',
    'add a neon color palette',
    'add a neon contrast',
    'add a neon brightness',
    'add a neon saturation',
    'add a neon temperature',
    'add a neon tone curve',
    'add a neon hue',
    'add a neon vibrance',
    'add a neon clarity',
    'add a neon structure',
    'add a neon detail',
    'add a neon sharpness',
    'add a neon focus',
    'add a neon depth of field',
    'add a neon bokeh',
    'add a neon motion blur',
    'add a neon lens flare',
    'add a neon film grain',
    'add a neon ripple',
    'add a neon smoke',
    'add a neon mist',
    'add a neon fog',
    'add a neon bubble',
    'add a neon particle',
    'add a neon sparkle',
    'add a neon confetti',
    'add a neon raindrop',
    'add a neon snow overlay',
    'add a neon light leak',
    'add a neon sun flare',
    'add a neon neon glow',
    'add a neon cartoon outline',
    'add a neon pencil sketch',
    'add a neon charcoal sketch',
    'add a neon pastel effect',
    'add a neon chalk scribble',
    'add a neon blueprint grid',
    'add a neon circuit pattern',
    'add a neon torn paper',
    'add a neon crumpled paper',
    'add a neon old photo border',
    'add a neon Polaroid frame',
    'add a neon vintage frame',
    'add a neon matte painting',
    'add a neon watercolor splash',
    'add a neon ink blot',
    'add a neon stain',
    'add a neon streak',
    'add a neon drop shadow',
    'add a neon mirror reflection',
    'add a neon thermal map',
    'add a neon infrared map',
    'add a neon X-ray effect',
    'add a neon UV effect',
    'add a neon comic bubble',
    'add a neon speech bubble',
    'add a neon barcode',
    'add a neon QR code',
    'add a neon wireframe overlay',
    'add a neon 3D cube',
    'add a neon 3D sphere',
    'add a neon 3D cylinder',
    'add a neon 3D pyramid',
    'add a neon 3D cone',
    'add a neon 3D torus',
    'add a vintage background',
    'add a vintage edges',
    'add a vintage center',
    'add a vintage subject',
    'add a vintage foreground',
    'add a vintage entire image',
    'add a vintage corners',
    'add a vintage highlights',
    'add a vintage shadows',
    'add a vintage midtones',
    'add a vintage outline',
    'add a vintage silhouette',
    'add a vintage reflection',
    'add a vintage texture',
    'add a vintage color palette',
    'add a vintage contrast',
    'add a vintage brightness',
    'add a vintage saturation',
    'add a vintage temperature',
    'add a vintage tone curve',
    'add a vintage hue',
    'add a vintage vibrance',
    'add a vintage clarity',
    'add a vintage structure',
    'add a vintage detail',
    'add a vintage sharpness',
    'add a vintage focus',
    'add a vintage depth of field',
    'add a vintage bokeh',
    'add a vintage motion blur',
    'add a vintage lens flare',
    'add a vintage film grain',
    'add a vintage ripple',
    'add a vintage smoke',
    'add a vintage mist',
    'add a vintage fog',
    'add a vintage bubble',
    'add a vintage particle',
    'add a vintage sparkle',
    'add a vintage confetti',
    'add a vintage raindrop',
    'add a vintage snow overlay',
    'add a vintage light leak',
    'add a vintage sun flare',
    'add a vintage neon glow',
    'add a vintage cartoon outline',
    'add a vintage pencil sketch',
    'add a vintage charcoal sketch',
    'add a vintage pastel effect',
    'add a vintage chalk scribble',
    'add a vintage blueprint grid',
    'add a vintage circuit pattern',
]


negative_prompts = [
    'remove the main subject',
    'remove the foreground',
    'remove the background',
    'remove all colors',
    'remove the color information',
    'remove the texture',
    'remove the shape',
    'remove the form',
    'remove the details',
    'remove the edges',
    'remove the highlights',
    'remove the shadows',
    'remove the entire image',
    'remove the focal point',
    'remove the central object',
    'remove the silhouette',
    'remove the outlines',
    'remove all recognizable features',
    'remove the perspective',
    'remove the depth cues',
    'remove the lighting',
    'remove the reflections',
    'remove the patterns',
    'remove the composition',
    'remove the structure',
    'remove the contours',
    'remove the geometry',
    'remove the semantic content',
    'remove the scene',
    'remove the context',
    'erase the main subject',
    'erase the foreground',
    'erase the background',
    'erase all colors',
    'erase the color information',
    'erase the texture',
    'erase the shape',
    'erase the form',
    'erase the details',
    'erase the edges',
    'erase the highlights',
    'erase the shadows',
    'erase the entire image',
    'erase the focal point',
    'erase the central object',
    'erase the silhouette',
    'erase the outlines',
    'erase all recognizable features',
    'erase the perspective',
    'erase the depth cues',
    'erase the lighting',
    'erase the reflections',
    'erase the patterns',
    'erase the composition',
    'erase the structure',
    'erase the contours',
    'erase the geometry',
    'erase the semantic content',
    'erase the scene',
    'erase the context',
    'obliterate the main subject',
    'obliterate the foreground',
    'obliterate the background',
    'obliterate all colors',
    'obliterate the color information',
    'obliterate the texture',
    'obliterate the shape',
    'obliterate the form',
    'obliterate the details',
    'obliterate the edges',
    'obliterate the highlights',
    'obliterate the shadows',
    'obliterate the entire image',
    'obliterate the focal point',
    'obliterate the central object',
    'obliterate the silhouette',
    'obliterate the outlines',
    'obliterate all recognizable features',
    'obliterate the perspective',
    'obliterate the depth cues',
    'obliterate the lighting',
    'obliterate the reflections',
    'obliterate the patterns',
    'obliterate the composition',
    'obliterate the structure',
    'obliterate the contours',
    'obliterate the geometry',
    'obliterate the semantic content',
    'obliterate the scene',
    'obliterate the context',
    'destroy the main subject',
    'destroy the foreground',
    'destroy the background',
    'destroy all colors',
    'destroy the color information',
    'destroy the texture',
    'destroy the shape',
    'destroy the form',
    'destroy the details',
    'destroy the edges',
    'destroy the highlights',
    'destroy the shadows',
    'destroy the entire image',
    'destroy the focal point',
    'destroy the central object',
    'destroy the silhouette',
    'destroy the outlines',
    'destroy all recognizable features',
    'destroy the perspective',
    'destroy the depth cues',
    'destroy the lighting',
    'destroy the reflections',
    'destroy the patterns',
    'destroy the composition',
    'destroy the structure',
    'destroy the contours',
    'destroy the geometry',
    'destroy the semantic content',
    'destroy the scene',
    'destroy the context',
    'scramble the main subject',
    'scramble the foreground',
    'scramble the background',
    'scramble all colors',
    'scramble the color information',
    'scramble the texture',
    'scramble the shape',
    'scramble the form',
    'scramble the details',
    'scramble the edges',
    'scramble the highlights',
    'scramble the shadows',
    'scramble the entire image',
    'scramble the focal point',
    'scramble the central object',
    'scramble the silhouette',
    'scramble the outlines',
    'scramble all recognizable features',
    'scramble the perspective',
    'scramble the depth cues',
    'scramble the lighting',
    'scramble the reflections',
    'scramble the patterns',
    'scramble the composition',
    'scramble the structure',
    'scramble the contours',
    'scramble the geometry',
    'scramble the semantic content',
    'scramble the scene',
    'scramble the context',
    'shatter the main subject',
    'shatter the foreground',
    'shatter the background',
    'shatter all colors',
    'shatter the color information',
    'shatter the texture',
    'shatter the shape',
    'shatter the form',
    'shatter the details',
    'shatter the edges',
    'shatter the highlights',
    'shatter the shadows',
    'shatter the entire image',
    'shatter the focal point',
    'shatter the central object',
    'shatter the silhouette',
    'shatter the outlines',
    'shatter all recognizable features',
    'shatter the perspective',
    'shatter the depth cues',
    'shatter the lighting',
    'shatter the reflections',
    'shatter the patterns',
    'shatter the composition',
    'shatter the structure',
    'shatter the contours',
    'shatter the geometry',
    'shatter the semantic content',
    'shatter the scene',
    'shatter the context',
    'fragment the main subject',
    'fragment the foreground',
    'fragment the background',
    'fragment all colors',
    'fragment the color information',
    'fragment the texture',
    'fragment the shape',
    'fragment the form',
    'fragment the details',
    'fragment the edges',
    'fragment the highlights',
    'fragment the shadows',
    'fragment the entire image',
    'fragment the focal point',
    'fragment the central object',
    'fragment the silhouette',
    'fragment the outlines',
    'fragment all recognizable features',
    'fragment the perspective',
    'fragment the depth cues',
    'fragment the lighting',
    'fragment the reflections',
    'fragment the patterns',
    'fragment the composition',
    'fragment the structure',
    'fragment the contours',
    'fragment the geometry',
    'fragment the semantic content',
    'fragment the scene',
    'fragment the context',
    'anonymize the main subject',
    'anonymize the foreground',
    'anonymize the background',
    'anonymize all colors',
    'anonymize the color information',
    'anonymize the texture',
    'anonymize the shape',
    'anonymize the form',
    'anonymize the details',
    'anonymize the edges',
    'anonymize the highlights',
    'anonymize the shadows',
    'anonymize the entire image',
    'anonymize the focal point',
    'anonymize the central object',
    'anonymize the silhouette',
    'anonymize the outlines',
    'anonymize all recognizable features',
    'anonymize the perspective',
    'anonymize the depth cues',
    'anonymize the lighting',
    'anonymize the reflections',
    'anonymize the patterns',
    'anonymize the composition',
    'anonymize the structure',
    'anonymize the contours',
    'anonymize the geometry',
    'anonymize the semantic content',
    'anonymize the scene',
    'anonymize the context',
    'mask the main subject',
    'mask the foreground',
    'mask the background',
    'mask all colors',
    'mask the color information',
    'mask the texture',
    'mask the shape',
    'mask the form',
    'mask the details',
    'mask the edges',
    'mask the highlights',
    'mask the shadows',
    'mask the entire image',
    'mask the focal point',
    'mask the central object',
    'mask the silhouette',
    'mask the outlines',
    'mask all recognizable features',
    'mask the perspective',
    'mask the depth cues',
    'mask the lighting',
    'mask the reflections',
    'mask the patterns',
    'mask the composition',
    'mask the structure',
    'mask the contours',
    'mask the geometry',
    'mask the semantic content',
    'mask the scene',
    'mask the context',
    'smear the main subject',
    'smear the foreground',
    'smear the background',
    'smear all colors',
    'smear the color information',
    'smear the texture',
    'smear the shape',
    'smear the form',
    'smear the details',
    'smear the edges',
    'smear the highlights',
    'smear the shadows',
    'smear the entire image',
    'smear the focal point',
    'smear the central object',
    'smear the silhouette',
    'smear the outlines',
    'smear all recognizable features',
    'smear the perspective',
    'smear the depth cues',
    'smear the lighting',
    'smear the reflections',
    'smear the patterns',
    'smear the composition',
    'smear the structure',
    'smear the contours',
    'smear the geometry',
    'smear the semantic content',
    'smear the scene',
    'smear the context',
    'morph the main subject',
    'morph the foreground',
    'morph the background',
    'morph all colors',
    'morph the color information',
    'morph the texture',
    'morph the shape',
    'morph the form',
    'morph the details',
    'morph the edges',
    'morph the highlights',
    'morph the shadows',
    'morph the entire image',
    'morph the focal point',
    'morph the central object',
    'morph the silhouette',
    'morph the outlines',
    'morph all recognizable features',
    'morph the perspective',
    'morph the depth cues',
    'morph the lighting',
    'morph the reflections',
    'morph the patterns',
    'morph the composition',
    'morph the structure',
    'morph the contours',
    'morph the geometry',
    'morph the semantic content',
    'morph the scene',
    'morph the context',
    'invert the main subject',
    'invert the foreground',
    'invert the background',
    'invert all colors',
    'invert the color information',
    'invert the texture',
    'invert the shape',
    'invert the form',
    'invert the details',
    'invert the edges',
    'invert the highlights',
    'invert the shadows',
    'invert the entire image',
    'invert the focal point',
    'invert the central object',
    'invert the silhouette',
    'invert the outlines',
    'invert all recognizable features',
    'invert the perspective',
    'invert the depth cues',
    'invert the lighting',
    'invert the reflections',
    'invert the patterns',
    'invert the composition',
    'invert the structure',
    'invert the contours',
    'invert the geometry',
    'invert the semantic content',
    'invert the scene',
    'invert the context',
    'randomize the main subject',
    'randomize the foreground',
    'randomize the background',
    'randomize all colors',
    'randomize the color information',
    'randomize the texture',
    'randomize the shape',
    'randomize the form',
    'randomize the details',
    'randomize the edges',
    'randomize the highlights',
    'randomize the shadows',
    'randomize the entire image',
    'randomize the focal point',
    'randomize the central object',
    'randomize the silhouette',
    'randomize the outlines',
    'randomize all recognizable features',
    'randomize the perspective',
    'randomize the depth cues',
    'randomize the lighting',
    'randomize the reflections',
    'randomize the patterns',
    'randomize the composition',
    'randomize the structure',
    'randomize the contours',
    'randomize the geometry',
    'randomize the semantic content',
    'randomize the scene',
    'randomize the context',
    'glitch the main subject',
    'glitch the foreground',
    'glitch the background',
    'glitch all colors',
    'glitch the color information',
    'glitch the texture',
    'glitch the shape',
    'glitch the form',
    'glitch the details',
    'glitch the edges',
    'glitch the highlights',
    'glitch the shadows',
    'glitch the entire image',
    'glitch the focal point',
    'glitch the central object',
    'glitch the silhouette',
    'glitch the outlines',
    'glitch all recognizable features',
    'glitch the perspective',
    'glitch the depth cues',
    'glitch the lighting',
    'glitch the reflections',
    'glitch the patterns',
    'glitch the composition',
    'glitch the structure',
    'glitch the contours',
    'glitch the geometry',
    'glitch the semantic content',
    'glitch the scene',
    'glitch the context',
    'obscure the main subject',
    'obscure the foreground',
    'obscure the background',
    'obscure all colors',
    'obscure the color information',
    'obscure the texture',
    'obscure the shape',
    'obscure the form',
    'obscure the details',
    'obscure the edges',
    'obscure the highlights',
    'obscure the shadows',
    'obscure the entire image',
    'obscure the focal point',
    'obscure the central object',
    'obscure the silhouette',
    'obscure the outlines',
    'obscure all recognizable features',
    'obscure the perspective',
    'obscure the depth cues',
    'obscure the lighting',
    'obscure the reflections',
    'obscure the patterns',
    'obscure the composition',
    'obscure the structure',
    'obscure the contours',
    'obscure the geometry',
    'obscure the semantic content',
    'obscure the scene',
    'obscure the context',
    'swap the main subject',
    'swap the foreground',
    'swap the background',
    'swap all colors',
    'swap the color information',
    'swap the texture',
    'swap the shape',
    'swap the form',
    'swap the details',
    'swap the edges',
    'swap the highlights',
    'swap the shadows',
    'swap the entire image',
    'swap the focal point',
    'swap the central object',
    'swap the silhouette',
    'swap the outlines',
    'swap all recognizable features',
    'swap the perspective',
    'swap the depth cues',
    'swap the lighting',
    'swap the reflections',
    'swap the patterns',
    'swap the composition',
    'swap the structure',
    'swap the contours',
    'swap the geometry',
    'swap the semantic content',
    'swap the scene',
    'swap the context',
    'replace the main subject',
    'replace the foreground',
    'replace the background',
    'replace all colors',
    'replace the color information',
    'replace the texture',
    'replace the shape',
    'replace the form',
    'replace the details',
    'replace the edges',
    'replace the highlights',
    'replace the shadows',
    'replace the entire image',
    'replace the focal point',
    'replace the central object',
    'replace the silhouette',
    'replace the outlines',
    'replace all recognizable features',
    'replace the perspective',
    'replace the depth cues',
    'replace the lighting',
    'replace the reflections',
    'replace the patterns',
    'replace the composition',
    'replace the structure',
    'replace the contours',
    'replace the geometry',
    'replace the semantic content',
    'replace the scene',
    'replace the context',
    'displace the main subject',
    'displace the foreground',
    'displace the background',
    'displace all colors',
    'displace the color information',
    'displace the texture',
    'displace the shape',
    'displace the form',
    'displace the details',
    'displace the edges',
    'displace the highlights',
    'displace the shadows',
    'displace the entire image',
    'displace the focal point',
    'displace the central object',
    'displace the silhouette',
    'displace the outlines',
    'displace all recognizable features',
    'displace the perspective',
    'displace the depth cues',
    'displace the lighting',
    'displace the reflections',
    'displace the patterns',
    'displace the composition',
    'displace the structure',
    'displace the contours',
    'displace the geometry',
    'displace the semantic content',
    'displace the scene',
    'displace the context',
    'blank out the main subject',
    'blank out the foreground',
    'blank out the background',
    'blank out all colors',
    'blank out the color information',
    'blank out the texture',
    'blank out the shape',
    'blank out the form',
    'blank out the details',
    'blank out the edges',
    'blank out the highlights',
    'blank out the shadows',
    'blank out the entire image',
    'blank out the focal point',
    'blank out the central object',
    'blank out the silhouette',
    'blank out the outlines',
    'blank out all recognizable features',
    'blank out the perspective',
    'blank out the depth cues',
    'blank out the lighting',
    'blank out the reflections',
    'blank out the patterns',
    'blank out the composition',
    'blank out the structure',
    'blank out the contours',
    'blank out the geometry',
    'blank out the semantic content',
    'blank out the scene',
    'blank out the context',
    'pixelate the main subject',
    'pixelate the foreground',
    'pixelate the background',
    'pixelate all colors',
    'pixelate the color information',
    'pixelate the texture',
    'pixelate the shape',
    'pixelate the form',
    'pixelate the details',
    'pixelate the edges',
    'pixelate the highlights',
    'pixelate the shadows',
    'pixelate the entire image',
    'pixelate the focal point',
    'pixelate the central object',
    'pixelate the silhouette',
    'pixelate the outlines',
    'pixelate all recognizable features',
    'pixelate the perspective',
    'pixelate the depth cues',
    'pixelate the lighting',
    'pixelate the reflections',
    'pixelate the patterns',
    'pixelate the composition',
    'pixelate the structure',
    'pixelate the contours',
    'pixelate the geometry',
    'pixelate the semantic content',
    'pixelate the scene',
    'pixelate the context',
    'explode the main subject',
    'explode the foreground',
    'explode the background',
    'explode all colors',
    'explode the color information',
    'explode the texture',
    'explode the shape',
    'explode the form',
    'explode the details',
    'explode the edges',
    'explode the highlights',
    'explode the shadows',
    'explode the entire image',
    'explode the focal point',
    'explode the central object',
    'explode the silhouette',
    'explode the outlines',
    'explode all recognizable features',
    'explode the perspective',
    'explode the depth cues',
    'explode the lighting',
    'explode the reflections',
    'explode the patterns',
    'explode the composition',
    'explode the structure',
    'explode the contours',
    'explode the geometry',
    'explode the semantic content',
    'explode the scene',
    'explode the context',
    'scramble the main subject',
    'scramble the foreground',
    'scramble the background',
    'scramble all colors',
    'scramble the color information',
    'scramble the texture',
    'scramble the shape',
    'scramble the form',
    'scramble the details',
    'scramble the edges',
    'scramble the highlights',
    'scramble the shadows',
    'scramble the entire image',
    'scramble the focal point',
    'scramble the central object',
    'scramble the silhouette',
    'scramble the outlines',
    'scramble all recognizable features',
    'scramble the perspective',
    'scramble the depth cues',
    'scramble the lighting',
    'scramble the reflections',
    'scramble the patterns',
    'scramble the composition',
    'scramble the structure',
    'scramble the contours',
    'scramble the geometry',
    'scramble the semantic content',
    'scramble the scene',
    'scramble the context',
    'distort the main subject',
    'distort the foreground',
    'distort the background',
    'distort all colors',
    'distort the color information',
    'distort the texture',
    'distort the shape',
    'distort the form',
    'distort the details',
    'distort the edges',
    'distort the highlights',
    'distort the shadows',
    'distort the entire image',
    'distort the focal point',
    'distort the central object',
    'distort the silhouette',
    'distort the outlines',
    'distort all recognizable features',
    'distort the perspective',
    'distort the depth cues',
    'distort the lighting',
    'distort the reflections',
    'distort the patterns',
    'distort the composition',
    'distort the structure',
    'distort the contours',
    'distort the geometry',
    'distort the semantic content',
    'distort the scene',
    'distort the context',
    'twist the main subject',
    'twist the foreground',
    'twist the background',
    'twist all colors',
    'twist the color information',
    'twist the texture',
    'twist the shape',
    'twist the form',
    'twist the details',
    'twist the edges',
    'twist the highlights',
    'twist the shadows',
    'twist the entire image',
    'twist the focal point',
    'twist the central object',
    'twist the silhouette',
    'twist the outlines',
    'twist all recognizable features',
    'twist the perspective',
    'twist the depth cues',
    'twist the lighting',
    'twist the reflections',
    'twist the patterns',
    'twist the composition',
    'twist the structure',
    'twist the contours',
    'twist the geometry',
    'twist the semantic content',
    'twist the scene',
    'twist the context',
    'erase the main subject',
    'erase the foreground',
    'erase the background',
    'erase all colors',
    'erase the color information',
    'erase the texture',
    'erase the shape',
    'erase the form',
    'erase the details',
    'erase the edges',
    'erase the highlights',
    'erase the shadows',
    'erase the entire image',
    'erase the focal point',
    'erase the central object',
    'erase the silhouette',
    'erase the outlines',
    'erase all recognizable features',
    'erase the perspective',
    'erase the depth cues',
    'erase the lighting',
    'erase the reflections',
    'erase the patterns',
    'erase the composition',
    'erase the structure',
    'erase the contours',
    'erase the geometry',
    'erase the semantic content',
    'erase the scene',
    'erase the context',
    'wipe the main subject',
    'wipe the foreground',
    'wipe the background',
    'wipe all colors',
    'wipe the color information',
    'wipe the texture',
    'wipe the shape',
    'wipe the form',
    'wipe the details',
    'wipe the edges',
    'wipe the highlights',
    'wipe the shadows',
    'wipe the entire image',
    'wipe the focal point',
    'wipe the central object',
    'wipe the silhouette',
    'wipe the outlines',
    'wipe all recognizable features',
    'wipe the perspective',
    'wipe the depth cues',
    'wipe the lighting',
    'wipe the reflections',
    'wipe the patterns',
    'wipe the composition',
    'wipe the structure',
    'wipe the contours',
    'wipe the geometry',
    'wipe the semantic content',
    'wipe the scene',
    'wipe the context',
    'deface the main subject',
    'deface the foreground',
    'deface the background',
    'deface all colors',
    'deface the color information',
    'deface the texture',
    'deface the shape',
    'deface the form',
    'deface the details',
    'deface the edges',
    'deface the highlights',
    'deface the shadows',
    'deface the entire image',
    'deface the focal point',
    'deface the central object',
    'deface the silhouette',
    'deface the outlines',
    'deface all recognizable features',
    'deface the perspective',
    'deface the depth cues',
    'deface the lighting',
    'deface the reflections',
    'deface the patterns',
    'deface the composition',
    'deface the structure',
    'deface the contours',
    'deface the geometry',
    'deface the semantic content',
    'deface the scene',
    'deface the context',
]
