train_data:
  parquet_image:
    - /datasets/datacomp/current/recap_datacomp_1b_data/
  parquet_text:
    - /datasets/datacomp/current/recap_datacomp_1b_data/
  webdataset:
    - /datasets/datacomp/current/recap_datacomp_1b_data/{00000..30000}.tar
  triplet_image_text:
    - .