train_data:
  parquet_image:
    - /home/terran/datacomp/recap_datacomp_1b_data/
  parquet_text:
    - /home/terran/datacomp/recap_datacomp_1b_data/
  webdataset:
    - /home/terran/datacomp/recap_datacomp_1b_data/{00000..30000}.tar
  triplet_image_text:
    - .